config/routes.rb
Rails.application.routes.draw do
  # Página raíz
  root 'home#index'
  
  # Devise
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_for :admins, path: 'admin', controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  # Recursos para usuarios
  resources :users, only: [:show, :edit, :update]

  # Ruta personalizada para el dashboard de usuarios
  get 'dashboard', to: 'users#dashboard', as: :dashboard

  # Encuestas y respuestas
  resources :surveys do
    resources :responses, only: [:new, :create, :index, :show]
  end

  # Propuestas
  resources :propuestas, only: [:index, :create]
  resources :proposals, only: [:create]

  # Recomendaciones
  resources :recommendations, only: [:index]

  # Estadísticas
  resources :user_statistics, only: [] do
    collection do
      get :personalized
      get :recommendations
    end
  end

  namespace :admin do
    resources :statistics, only: [] do
      collection do
        get :general
      end
    end
  end
end

app/models/user.rb
# app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  include BCrypt
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Asociaciones
  has_many :surveys, dependent: :destroy

  # Validaciones
  validates :name, presence: true
  validates :gender, inclusion: { in: %w[male female], message: "%{value} no es un género válido" }
  validates :age, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 100, message: "debe estar entre 1 y 100 años" }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: "no tiene un formato valido" }
  validates :weight, numericality: { greater_than: 0, message: "debe ser un número positivo" }, allow_nil: true
  validates :height, numericality: { greater_than: 0, message: "debe ser un número positivo" }, allow_nil: true
  validates :password, length: { minimum: 8, message: "debe tener al menos 8 caracteres" }, format: { with: /\A.*(?=.*[!@#$%^&*])(?=.*[A-Za-z]).*\z/, message: "debe incluir al menos una letra y un signo especial" }
  validates :encrypted_password, presence: true

  # Métodos personalizados
  # Setter para encriptar la contraseña antes de guardarla
  def password=(plain_password)
    return if plain_password.blank?

    self.encrypted_password = BCrypt::Password.create(plain_password)
  end

  # Método para autenticar usuarios
  def authenticate(plain_password)
    Password.new(self.encrypted_password) == plain_password
  end
  
  def imc
    return nil if height.nil? || weight.nil? || height.zero?

    (weight / (height**2)).round(2)
  end

  def imc_label
    case imc
    when nil then "No calculado"
    when 0..18.4 then "Bajo peso"
    when 18.5..24.9 then "Normal"
    when 25..29.9 then "Sobrepeso"
    else "Obesidad"
    end
  end

  def ideal_sleep_hours
    gender == "male" ? 7.5 : 8
  end

  def full_profile?
    name.present? && age.present? && gender.present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user! # Requiere autenticación con Devise
  before_action :set_user, only: %i[show edit update]

  rescue_from ActiveRecord::RecordInvalid, with: :handle_record_invalid

  # Acción pública para el dashboard
  def dashboard
    @surveys = current_user.surveys
    @recommendations = Recommendation.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: "Usuario creado con éxito."
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Perfil actualizado correctamente.'
    else
      render :edit
    end
  end

  private

  def handle_record_invalid(exception)
    flash[:alert] = "Hubo un error al procesar tu solicitud: #{exception.record.errors.full_messages.join(', ')}"
    redirect_to request.referer || root_path
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :age, :gender, :occupation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_chart.html.erb
<div class="chart">
  <h3><%= title %></h3>
  <%= pie_chart chart_data, colors: ['#4CAF50', '#FFC107', '#F44336'], donut: true %>
  <%= line_chart [ name: "IMC", data: { "Semana 1" => 22.3, "Semana 2" => 23.5, "Semana 3" => 21.8 } ] %>
<p>Etiqueta actual: <%= @user.imc_label %></p>
</div>

app/views/users/_from.html.erb
<%= form_with model: user, local: true do |f| %>
  <div class="form-group">
    <%= f.label :name, 'Nombre' %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Ingresa tu nombre' %>
  </div>

  <div class="form-group">
    <%= f.label :email, 'Email' %>
    <%= f.email_field :email, class: 'form-control', placeholder: 'Ingresa tu correo' %>
  </div>

  <div class="form-group">
    <%= f.label :age, 'Edad' %>
    <%= f.number_field :age, class: 'form-control', placeholder: 'Ingresa tu edad' %>
  </div>

  <div class="form-group">
    <%= f.label :age, 'Talla' %>
    <%= f.number_field :age, class: 'form-control', placeholder: '¿Cuánto mide en cm?' %>
  </div>

  <div class="form-group">
    <%= f.label :age, 'Peso' %>
    <%= f.number_field :age, class: 'form-control', placeholder: '¿Cuál es tu peso en Kg?' %>
  </div>

  <div class="form-group">
    <%= f.label :gender, 'Género' %>
    <%= f.select :gender, [['Masculino', 'male'], ['Femenino', 'female']], 
                 { prompt: 'Selecciona tu género' }, 
                 class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :occupation, 'Ocupación' %>
    <%= f.text_field :occupation, class: 'form-control', placeholder: ' ¿A qué te dedicas? ' %>
  </div>

  <%= f.submit 'Guardar', class: 'btn btn-primary' %>
<% end %>

app/views/users/dashboard.html.erb
<h1>Bienvenido, <%= current_user.name %></h1>

<h2>Tus Estadísticas</h2>
<div>
  <%= render partial: 'users/_chart', locals: { chart_data: @imc_data, title: 'Horas de Sueño' } %>
</div>
<div>
  <%= render partial: 'users/_chart', locals: { chart_data: @activity_data, title: 'Nivel de Actividad Física' } %>
</div>

<h2>Tus Encuestas</h2>
<table>
  <thead>
    <tr>
      <th>Establecimiento</th>
      <th>Fecha</th>
      <th>Cantidad de Usuarios</th>
    </tr>
  </thead>
  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.title %></td>
        <td><%= survey.establishment.name %></td>
        <td><%= survey.created_at.strftime('%d/%m/%Y') %></td>
        <td>
          <%= link_to 'Ver', survey_path(survey), class: 'btn btn-info' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Recomendaciones para ti</h2>
<ul>
  <% @recommendations.each do |rec| %>
    <li><strong><%= rec.title %>:</strong> <%= rec.content %></li>

    <p><strong>Promedio de Actividad Física:</strong> <%= @user_activity_avg.round(2) %> minutos/semana</p>
<p>
  <% if @user_activity_avg < 150 %>>
    Recomendación: Incrementa tu actividad física hasta al menos 150 minutos/semana.
  <% else %>
    ¡Buen trabajo! Estás alcanzando el nivel recomendado por la OMS.
  <% end %>
</p>

<p>
  <% if @user_activity_avg < 150 %>>
    Recomendación: Incrementa tu actividad física hasta al menos 150 minutos/semana.
  <% else %>
    ¡Buen trabajo! Estás alcanzando el nivel recomendado por la OMS.
  <% end %>
</p>

    <p><strong>Promedio de Horas de Sueño:</strong> <%= @user_imc_avg.round(2) %> horas</p>
<p>
  <% if @user_imc_avg < 7 %>
    Recomendación: Dormir más tiempo para mejorar la salud general.
  <% elsif @user_imc_avg > 9 %>
    Recomendación: Considera equilibrar el sueño con actividad física.
  <% else %>
    ¡Tu promedio está dentro del rango ideal! Sigue así.
  <% end %>

  <p><strong>Indice de masa Corporal:</strong> <%= @user_imc_avg.round(2) %> horas</p>
<p>
  <% if @user_imc_avg = "Bajo peso" %>
    Recomendación: Aumenta tu ingesta calórica diaria con alimentos saludables
  <% elsif @user_imc_avg = "Normal" %>
    Recomendación: ¡Sigue con tus hábitos actuales!
  <% elsif @user_imc_avg = "Sobrepeso" %>
    Recomendación: Consulta a un especialista para más detalles.
  <% end %>
  <% end %>
</ul>

app/views/users/edit.html.erb
<h1>Editar Perfil</h1>

<%= render 'form', user: @user %>

<%= link_to 'Cancelar', user_path(@user), class: 'btn btn-secondary' %>

app/views/users/personalized.erb
<h1>Estadísticas Personalizadas</h1>

<p><strong>Indice de masa Corporal:</strong> <%= @.round(2) %> :</p>

<h2>Horas de Sueño Promedio</h2>
<%= bar_chart @sleep_comparison, colors: ["#F44336", "#4CAF50", "#FFC107"], height: "300px" %>

<h2>Nivel de Actividad Física</h2>
<%= pie_chart @activity_comparison, colors: ["#F44336", "#4CAF50"], height: "300px" %>

</p>

app/views/users/show.html.erb
<h1>Tu Perfil</h1>

<p><strong>Nombre:</strong> <%= @user.name %></p>
<p><strong>Email:</strong> <%= @user.email %></p>
<p><strong>Edad:</strong> <%= @user.age %></p>
<p><strong>Género:</strong> <%= @user.gender %></p>
<p><strong>Talla:</strong> <%= @user.talla %></p>
<p><strong>Peso:</strong> <%= @user.peso %></p>
<p><strong>Ocupación:</strong> <%= @user.occupation %></p>

<%= link_to 'Editar Perfil', edit_user_path(@user), class: 'btn btn-warning' %>
<%= link_to 'Volver al Dashboard', dashboard_path, class: 'btn btn-secondary' %>